name: Deploy to Testnets

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Protocol release version (test/master/v1/etc.)'
        required: true
        default: 'test'
      only_network:
        description: 'Only a specific network is to be deployed'
        required: false

jobs:

  deploy-to-testnets:
    name: Deploy to testnets

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          network: [goerli, rinkeby, ropsten, mumbai]

    if: ${{ github.event.inputs.only_network == '' || github.event.inputs.only_network == matrix.network }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to ${{ matrix.network }}
        run: |
          cd packages/ethereum-contracts
          npx truffle exec --network ${{ matrix.network }} scripts/deploy-test-environment.js
          if ./tasks/supports-etherscan.sh ${{ matrix.network }};then
            npx truffle exec --network ${{ matrix.network }} scripts/print-addresses.js : addresses.vars
            source addresses.vars
            source tasks/etherscan-verify-framework.sh ${{ matrix.network }}
          fi
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GOERLI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
          GOERLI_PROVIDER_URL: ${{ secrets.GOERLI_PROVIDER_URL }}
          RINKEBY_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
          RINKEBY_PROVIDER_URL: ${{ secrets.RINKEBY_PROVIDER_URL }}
          ROPSTEN_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
          ROPSTEN_PROVIDER_URL: ${{ secrets.ROPSTEN_PROVIDER_URL }}
          MUMBAI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
          MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
